require('core.plugin_configs.colorscheme')
require('core.plugin_configs.commentary')
require('core.plugin_configs.lsp')
require('core.plugin_configs.lualine')
require('core.plugin_configs.nvimtree')
require('core.plugin_configs.telescope')
require('core.plugin_configs.treesitter')
